### ISSUE TITLE
Couldn't delete container

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-sdk-go#101]
Currently we can not delete container using `pool.Pool` without correct session token because despite omitting session token during container deletion the default one will be used (that isn't compatible with required container session token).

The following test shouldn't fail:
```go

import (
	"context"
	"fmt"
	"math"
	"strconv"
	"testing"
	"time"

	"github.com/nspcc-dev/neo-go/pkg/crypto/keys"
	"github.com/nspcc-dev/neofs-sdk-go/acl"
	"github.com/nspcc-dev/neofs-sdk-go/container"
	"github.com/nspcc-dev/neofs-sdk-go/policy"
	"github.com/nspcc-dev/neofs-sdk-go/pool"
	"github.com/stretchr/testify/require"
)

func TestContainerDelete(t *testing.T) {
	ctx := context.Background()

	// have to use key with sufficient amount of gas to create container
	key, err := keys.NewPrivateKey()
	require.NoError(t, err)

	pb := new(pool.Builder)
	pb.AddNode("s01.neofs.devenv:8080", 1, 1)

	opts := &pool.BuilderOptions{
		Key:                     &key.PrivateKey,
		NodeConnectionTimeout:   4 * time.Second,
		NodeRequestTimeout:      4 * time.Second,
		ClientRebalanceInterval: 40 * time.Second,
		SessionExpirationEpoch:  math.MaxUint32,
	}

	p, err := pb.Build(ctx, opts)
	require.NoError(t, err)

	pp, err := policy.Parse("REP 3")
	require.NoError(t, err)

	cnr := container.New(
		container.WithPolicy(pp),
		container.WithOwnerID(p.OwnerID()),
		container.WithCustomBasicACL(acl.ReadOnlyBasicRule))

	cnrID, err := p.PutContainer(ctx, cnr)
	require.NoError(t, err)

	fmt.Println(cnrID)

	err = p.WaitForContainerPresence(ctx, cnrID, pool.DefaultPollingParams())
	require.NoError(t, err)

	err = p.DeleteContainer(ctx, cnrID)
	require.NoError(t, err)

	time.Sleep(3 * time.Second)

	_, err = p.GetContainer(ctx, cnrID)
	require.Error(t, err)
}

```

**Comment by alexvanin** [comment]
First check in NeoFS SN that it does not process session token with object context as token with empty container context in container service.

Then we may ignore default session token in all container related operations in pool.

**Comment by alexvanin** [comment]
> First check in NeoFS SN that it does not process session token with object context as token with empty container context in container service.

Storage node attaches any token that client provided. If client provides session token without container context, it does not throw any errors. It should be fixed in https://github.com/nspcc-dev/neofs-node/issues/1045

Meantime pool should not attach session tokens to container service requests.
