### ISSUE TITLE
NNS and DNS support for human friendly container names

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-sdk-go#11]
**Problem**
It may not be convenient for humans to operate with NeoFS low level `ContainerID` and `ObjectID`.

**Proposed solution**
Use NNS to allow looking up `ContainerID` by it's domain and friendly name string. It should be also possible to mirror the same mechanism for regular DNS to simplify application client-side development.

**Comment by realloc** [comment]
Recently, we came to an agreement to have a well-known ID for the NNS contract in SideChain. Human-friendly address aliases may be stored there, additionally to the NNS in mainnet. If there will be a DNS zone mapped to the NNS records, we have two more possible sources for aliases.

Hence, the resolver module has to work with NNS or DNS, depending on the configuration.

**Comment by alexvanin** [comment]
So basically we want to expand NeoFS API Client interface with DNS \ NNS support. Client should:
- support TXT names of the container,
- support endpoint to DNS server.
- resolve container names.

Unfortunately, client is still in neofs-api-go repository.
