### ISSUE TITLE
Extra value for Clause

### ISSUE THREAD

**Issue by ZhangTao1596** [nspcc-dev/neofs-sdk-go#112]
Now we only have two types *Clause*: `Same` and `Distinct`(Unspecify is actually distinct). But some times we have enough nodes in reality but we can't get enough selected nodes whether we use `Same` or `Distinct` in policy. Take following as an example.

Suppose there are 4 nodes with specific country:
```
[
    { "attributes": [ { "key": "Country", "value": "Russia" } ] },
    { "attributes": [ { "key": "Country", "value": "Russia" } ] },
    { "attributes": [ { "key": "Country", "value": "Germany" } ] },
    { "attributes": [ { "key": "Country", "value": "China" } ] }
] 
```
If I want 3 nodes not from China, whether I use policy(different in Clause) `REP 1 CBF 1 SELECT 3 IN SAME Country FROM notCN FILTER Country NE China AS notCN` or `REP 1 CBF 1 SELECT 3 IN DISTINCT Country FROM notCN FILTER Country NE China AS notCN`, I can't get enough nodes. We have 3 nodes not in China but I can't select them.

**Comment by fyrchik** [comment]
`SELECT` is used to group nodes in buckets, so both policies in your post work as expected. You can still select 3 nodes outside China, e.g. by omitting attribute to perform grouping on: `REP 1 CBF 1 SELECT 3 FROM notCN FILTER Country NE China AS notCN`. This way we will just select 3 distinct nodes which satisfy `notCN` filter.

**Comment by ZhangTao1596** [comment]
> `SELECT` is used to group nodes in buckets, so both policies in your post work as expected. You can still select 3 nodes outside China, e.g. by omitting attribute to perform grouping on: `REP 1 CBF 1 SELECT 3 FROM notCN FILTER Country NE China AS notCN`. This way we will just select 3 distinct nodes which satisfy `notCN` filter.

I see. Thanks. I'm closing this.
