### ISSUE TITLE
Support `ALREADY_EXISTS` status of `ContainerPut`

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#138]
## Context
In current version NeoFS system does not give a feedback on the creation of an already existing container (`Container.Put`). There are some need of `PutIfNotExists` operation, which is not supported in NeoFS API V2 protocol (originally posted by @KirillovDenis @masterSplinter01 @realloc in [NeoFS S3 Gateway](https://github.com/nspcc-dev/neofs-s3-gw/) project).

## Overview

We can support using current behavior of PUT and GET ops:

1. call GET, return on error;
2. compare binary formats of current and already stored containers, and return `ErrAlreadyExists` if they are similar (*);
3. call PUT.

\* we can also compare owners (for some need of S3 mentioned by @KirillovDenis).

## P.S.
Since containers are content-addressed, there can be a surprise in `2.` when we received container by its ID and it differs binary. In NeoFS API V2 protocol it is impossible and this can only occur in the case of a malicious server, so it is worth considering such a case as an error, too.

According to NeoFS API V2 protocol, the client immediately receives the identifier of the container being created, even though it is written asynchronously. It implicitly follows from this that the structure of the container, formed by the user, <ins>must not</ins> be changed. We've decided with @realloc  that this fact should be <ins>emphasized</ins> in the NeoFS specification.

**Comment by alexvanin** [comment]
> We can support using current behavior of PUT and GET ops:

What about implementing existence check in container contract during test invoke? 
1. Call `container.Put`
2. Receive well-known panic message (like [NotFoundError](https://github.com/nspcc-dev/neofs-contract/blob/5758dadaa9c0791287d716fc2beaa0086bc4065c/container/container_contract.go#L74)
3. Parse and return `ErrAlreadyExist` status code.

**Comment by cthulhu-rider** [comment]
> Receive well-known panic message

This is an argument for native support in protocol of `Container.Put`.

**Comment by realloc** [comment]
I'd suggest not to change regular `Put` bahaviour. It should be an upsert-like warapper.

**Comment by alexvanin** [comment]
> I'd suggest not to change regular Put bahaviour. It should be an upsert-like warapper.

Upserting will be possible only in case of hash collision between two different containers with the same ID (which is extremely unlikely). You sure want to have two RPCs (Get, Put) instead of one?

**Comment by realloc** [comment]
I mean normal `Put` has to return `OK` if container already exists. Additional `PutIfNotExists`(name is random, may be a flag) has to make additional `Get` to check. But that's up to the developer to decide what call does he need according to application logic.

**Comment by alexvanin** [comment]
> I mean normal `Put` has to return `OK` if container already exists. Additional `PutIfNotExists`(name is random, may be a flag) has to make additional `Get` to check. But that's up to the developer to decide what call does he need according to application logic.

Just to be clear: on the protocol level `container.Put` returns `ALREADY_EXIST` status if container exists. Client (pool) library can ignore this error if specific flag is set \ unset (or invoked additional method).

**Comment by alexvanin** [comment]
It seems that we can't solve this issue with preliminary `container.Get` request. The reason is that main source of collisions in application is not container ID, but nicename. With random `nonce` it is highly unlikely that we will get the same container ID. 

NeoFS API does not provide nicename lookup. And it should not, I believe. We will have an error during `container.Put` that can be parsed by library or application.

I think it should not be parsed on library level, because it is not a part of protocol. Also nicename storage technically can be tied with other external domain controllers.

@cthulhu-rider can we close this issue?

**Comment by cthulhu-rider** [comment]
We can work with container IDs only, so for now it's not actual.
