### ISSUE TITLE
pool: support more user-friendly search 

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-sdk-go#148]
It would be nice to have search function that returns list of `oid.ID` in the pool.
In most service applications that use sdk we have to define the similar function:

```
func searchObjects(ctx context.Context, sdkPool pool.Pool, cnrID *cid.ID, filters object.SearchFilters) ([]oid.ID, error) {
	res, err := sdkPool.SearchObjects(ctx, *cnrID, filters)
	if err != nil {
		return nil, fmt.Errorf("init searching using client: %w", err)
	}

	defer res.Close()

	var num, read int
	buf := make([]oid.ID, 10)

	for {
		num, err = res.Read(buf[read:])
		if num > 0 {
			read += num
			buf = append(buf, oid.ID{})
			buf = buf[:cap(buf)]
		}

		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}

			return nil, fmt.Errorf("couldn't read found objects: %w", err)
		}
	}

	return buf[:read], nil
}
```

**Comment by cthulhu-rider** [comment]
Is there a need for flexible handling of the resulting slice, or is it mostly required to iterate over the elements? if so, I would recommend making the function an iterator for memory efficiency.

**Comment by KirillovDenis** [comment]
Most common use cases:
* Iterate over the elements to get/head objects
* Ensure that the resulting slice contains exactly one element and get/head it

**Comment by realloc** [comment]
If we implement a wrapper, there must be an argument limiting the number of OIDs in the returned result. We need this to prevent long time waiting|processing large search results.

**Comment by fyrchik** [comment]
@KirillovDenis could you provide a link to where this is used?

We can either have `(*ResObjectSearch).ReadAtMost` or `(*ResObjectSearch).Iterate` depending on what is more suitable.

**Comment by KirillovDenis** [comment]
https://github.com/nspcc-dev/distribution/blob/main/registry/storage/driver/neofs/neofs.go#L476
https://github.com/nspcc-dev/restic/blob/master/internal/backend/neofs/neofs.go#L139
https://github.com/nspcc-dev/rclone/blob/master/backend/neofs/neofs.go#L714

**Comment by cthulhu-rider** [comment]
We need to decide what method is more basic - `Read` or `Iterate` - and implement other operation as a function over the basic.

**Comment by KirillovDenis** [comment]
I think the `Iterate` is more basic for search

**Comment by fyrchik** [comment]
@KirillovDenis in the first 2 links _exactly_ one search result is expected. I don't think this check belongs to SDK as it to enforce some business logic invariants. Is it necessary to check this in the code you linked?

**Comment by KirillovDenis** [comment]
> @KirillovDenis in the first 2 links _exactly_ one search result is expected. I don't think this check belongs to SDK as it to enforce some business logic invariants. Is it necessary to check this in the code you linked?

It seems I didn't understand you question about links. I thought you need to see most common use cases (so I included different patterns of use). 
If we speak about iterating and making some actions the following links are more appropriate:
* https://github.com/nspcc-dev/distribution/blob/main/registry/storage/driver/neofs/neofs.go#L630
* https://github.com/nspcc-dev/restic/blob/master/internal/backend/neofs/neofs.go#L164

**Comment by cthulhu-rider** [comment]
* done in #156
