### ISSUE TITLE
Add function/method that allows get address from object

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-sdk-go#175]
Now it is possible to do only only using:
1. for string representation: `obj.ContainerID().String() + "/" + obj.ID().String()`
2. for `Address`:
```
addr := addressSDK.NewAddress()
addr.SetObjectID(obj.ID())
addr.SetContainerID(obj.ContainerID())
```

**Comment by cthulhu-rider** [comment]
The need to get the `address.Address` from the `object.Object` in most cases looks very redundant, usually you need to query the object by address. Can you give an example of a use case @carpawell?

**Comment by carpawell** [comment]
I faced the problem with notifications: an object with notification may be received by a node and the node must produce notification then (notification contains only address info).

There is [function](https://github.com/nspcc-dev/neofs-node/blob/master/pkg/core/object/object.go#L9) in the node that has 10+ usages.

**Comment by cthulhu-rider** [comment]
What about this function? https://github.com/nspcc-dev/neofs-sdk-go/blob/b006ade1546a1f862e83398940f750dfcf75f6ca/object/object.go#L341
Does `NotificationInfo` has all needed stuff?

**Comment by carpawell** [comment]
It has all info to define *when* and *where* send a notification but does not have info *what* to send (address info).

**Comment by carpawell** [comment]
It has all info to define *when* and *where* to send a notification but does not have info on *what* to send (address info).

**Comment by cthulhu-rider** [comment]
I got it. Don't you think we need to type _what_ to send?

**Comment by cthulhu-rider** [comment]
I mean if we send smth somewhere, we need to be able to decode it somewhere. So I suggest to type _what_ we send.

About other needs to pull out address from object - they are mostly for testing and logging.

**Comment by cthulhu-rider** [comment]
Postponed on after https://github.com/nspcc-dev/neofs-sdk-go/milestone/1.

**Comment by fyrchik** [comment]
We now have `object.AddressOf` and `EncodeToString` method on `Address`.
