### ISSUE TITLE
Drop `logger` package

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#177]
`logger` package provides functionality to work with application logging component. Loggers are application-specific features, so I propose to completely remove `logger` package from NeoFS SDK repo.

Current implementation is used in several projects, so we can either:

1. implement logger locally in each project
2. place current `logger` package in separate repo and share it between the projects

I'd prefer option 1.

**Comment by fyrchik** [comment]
Closed via #188.
