### ISSUE TITLE
Document mutability of reference types

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#187]
## Context
We pass, accept or return reference types in some functions: `map`, `[]T`, pointer etc. Each reference type can raise mutability issues. We must disclose in detail all such cases.

## Proposal
Don't accept value by reference if the function does not imply mutation, or in other special cases (for example, sometimes passing a value by a pointer leads to an improvement in runtime performance). 

We should reflect clearly in docs if arg/return should be read-only or it's mutation-free.

For example this method returns result by value not pointer:
```
func (x T) GetBytes() []byte {
  return x.b
}
```
but it's not clear if result mutations affect `T` instance (in this case yes). Docs can resolve it:
```
// GetBytes ...
//
// Mutation of the result affects T. Make a preliminary copy for direct mutation.
```

Other example (JFYI):
```
// GetBytes ...
//
// Result is mutation-free.
func (x T) GetBytes() []byte {
  b := make([]byte, len(x.b))
  copy(b, x.b)
  return b
}
```

**Comment by roman-khimov** [comment]
Why is it blocked? Because we don't yet have a final API? It's important to specify this for a good library.

**Comment by cthulhu-rider** [comment]
Yeah, it makes sense to do this after all code is ready. But ofc we can start now. In general, I wanted to determine the need for these actions.
