### ISSUE TITLE
Document formats of binary public keys

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#196]
* based on and blocked by https://github.com/nspcc-dev/neofs-api/issues/211

We should provide proper documentation for the binary format of transmitted cryptographic primitives like public keys. 

Example: https://github.com/nspcc-dev/neofs-sdk-go/blob/e50e6d28280d9fb751a944210d1eca61cc23c111/session/session.go#L98

**Comment by roman-khimov** [comment]
Is it still a problem? `SetAuthKey()` uses more appropriate type now and that's what I'd expect from SDK in general. Maybe in
```
audit/result.go:func (r Result) AuditorKey() []byte {
audit/result.go:func (r *Result) SetAuditorKey(key []byte) {
bearer/bearer.go:func (b Token) SigningKeyBytes() []byte {
client/response.go:func (x ResponseMetaInfo) ResponderKey() []byte {
client/session.go:func (x ResSessionCreate) PublicKey() []byte {
crypto/util.go:func StringifyKeyBinary(src []byte) string {
eacl/target.go:func (t *Target) BinaryKeys() [][]byte {
eacl/target.go:func (t *Target) SetBinaryKeys(keys [][]byte) {
eacl/types.go:func (u *ValidationUnit) WithSenderKey(v []byte) *ValidationUnit {
netmap/node_info.go:func (x *NodeInfo) SetPublicKey(key []byte) {
netmap/node_info.go:func (x NodeInfo) PublicKey() []byte {
reputation/peer.go:func (x *PeerID) SetPublicKey(key []byte) {
reputation/peer.go:func (x PeerID) PublicKey() []byte {
reputation/peer.go:func ComparePeerKey(peer PeerID, key []byte) bool {
```
Why we're still using `[]byte` here?

**Comment by smallhive** [comment]
I've done some research about [mentioned](https://github.com/nspcc-dev/neofs-sdk-go/issues/196#issuecomment-1413837350) methods in all gateways and node repos. GWs repos almost don't use these methods, but node uses a lot. But using public key like `[]byte` is a convenient way and there was just a couple places where we had some conversation to struct.

But I noticed, that sometime in the code public key from `[]byte` converts to a hex string via `hex.EncodeToString(key)`. For this purpose, we have `StringifyKeyBinary(src []byte) string`. It does the same job but in one place. May we should think about rewrite `hex.EncodeToString` to `StringifyKeyBinary`.

Conclusion: Using a public key as `[]byte` right now is an appropriate way than converting it to `esda.PublicKey` or any other structure.
