### ISSUE TITLE
pool: drop legacy error checking

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-sdk-go#207]
Someday we should roll back the PR https://github.com/nspcc-dev/neofs-sdk-go/pull/206

**Comment by alexvanin** [comment]
A bit of the context.

Right now we have neofs-node v0.27.x with NeoFS API v2.11 in both mainnet and testnet.
Next release of neofs-node v0.28.0 with NeoFS API v2.12 introduces status code `CONTAINER_NOT_FOUND`  in https://github.com/nspcc-dev/neofs-api/pull/196/commits/bc7c9e36df0bc5127892bd93cbdd4584e9983b82. 

We don't want to break compatibility immediately, so `pool` has to check both error types. After a while, when networks are going to be upgraded, we can drop error parsing and use only status codes.

**Comment by alexvanin** [comment]
/cc @KirillovDenis @masterSplinter01 

Check if SDK error handling works fine with v0.28.x. There might be some issues that require error unwrapping.

**Comment by KirillovDenis** [comment]
There is a problem with checking error. Consider the following code (try to get object via pool)
```
// ...
_, err = p.GetObject(ctx, prm)
fmt.Println(err)
fmt.Println(sdkClient.IsErrObjectNotFound(err))
err = errors.Unwrap(err)
fmt.Println(sdkClient.IsErrObjectNotFound(err))

// ...
```

It produce the following output:
```
read header: status: code = 2049 message = object not found
false
true
```

Checked on dev-env with storage node `v0.28.3`
