### ISSUE TITLE
client: Do not sign containers and eACL

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#209]
I propose to take out all signatures, except for transport ones, outside the `Client`. In current implementation we sign only containers, eACL and container removal witnesses. In these cases, the key cannot be any, so the signature by the `Client` is difficult to control, which can lead to unexpected behavior on the part of the user.

If we'll consider to support internal signing, it'll be a compatible behavior change, but not vice versa.

**Comment by roman-khimov** [comment]
Is it a problem now with reworked signers? Client can sign by default, but everything can be overridden if need be. Seems to be OK, isn't it? @smallhive?

**Comment by smallhive** [comment]
From my point of view it isn't a problem anymore because all signers maybe attached/overridden outside the client. And we also have backward compatibility with default signer, inside client

**Comment by cthulhu-rider** [comment]
I can init `client.Client` with any `neofscrypto.Signer`. If signer's scheme isn't RFC6979 one, default signature of container creation request will always be incorrect. To avoid this, https://pkg.go.dev/github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.8/client#PrmContainerPut.SetSigner must be required, and that's what this issue is about.

Besides, default signing is always thin ice when it affects authorization. I can create client with random volatile key which will "own" containers/objects/anything. This is completely undesired by apps.

**Comment by roman-khimov** [comment]
> If signer's scheme isn't RFC6979 one, default signature of container creation request will always be incorrect

So we need to check the signer passed to always be RFC6979 and that's it, isn't it?

>  https://pkg.go.dev/github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.8/client#PrmContainerPut.SetSigner

Or container (and other) operations can check their signers and return some error if the type doesn't match the expected one.

> I can create client with random volatile key 

You can randomly sign objects/operations as well, it's your (app) code. But my bet is that in most cases there is exactly one key being used to sign things when `Client` is incarnated. Complex cases like gateways are, well, complex, they do what they need to. But simple cases should be simple, "here is my key, do whatever is needed with it, just serve my requests" instead of signing each of them individually with the same key again and again.

**Comment by notimetoname** [comment]
I would:

1. expand the docs (even i had to fill the issue's context via the code, `SetSigner` says [too general words](https://github.com/nspcc-dev/neofs-sdk-go/blob/c97f834c6b5bbda6d0211759747a498ebeeb184e/client/container.go#L41) about its usage in that case);
2. make it impossible to use a signer that does not satisfy the requirements (returning an error about it is OK for me).

External signature does not solve the problem (wrong/random/broken/etc signature) if it just returns an error (the whole `ContainerPut` can make the same), IMO. Signing should be a part of SDK anyway, so i do not see the huge difference b/w a custom signature outside of the `ContainerPut` vs a custom signer created outside of the client creation. Users may do strange things but generally i expect a client to use the same key for the `Client` and for the `ContainerPut`. The gates are an exception but they know that they do and, moreover, their code owners also write and support SDK.

**Comment by cthulhu-rider** [comment]
the transition from general to specific (general-purpose `Signer` to fixed schema) is never easy to follow. For now, the documentation should suffice. It remains only to return an error for eye analysis

I'd consider this issue not actual anymore
