### ISSUE TITLE
Sync package/dir names

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#211]
Names of some packages differ with corresponding dirs. For example, `neofscrypto` package is placed in `crypto` dir, and package is named in order to avoid collision with standard package, while dir name is shortened since it is obviously NeoFS feature.

In this topic, I propose to fix the naming approach:

1. use current naming
2. sync naming with `neofs` substr
3. sync naming without `neofs` substr

For me the most convenient options are 1 and 2.

We can also explore approaches from the other projects. For example, Neo Go has [crypto](https://github.com/nspcc-dev/neo-go/tree/master/pkg/crypto) package.

**Comment by fyrchik** [comment]
I am for the 3-rd option, because (1) it is always annoys me when a package has a name different from it's path's basename and (2) we can think of some better names, like `signer`, `sign`? and (3) our `Signer` is actually a replacement for `Signer` from the stdlib.

**Comment by cthulhu-rider** [comment]
Decided to implement 3rd option.

**Comment by roman-khimov** [comment]
Anything that doesn't change import paths is OK.

**Comment by roman-khimov** [comment]
And the best thing to do is not do anything at all.
