### ISSUE TITLE
Extend private keys to signers where possible

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#212]
NeoFS protocol supports several signature schemes. In current implementation all signing functions accept `ecdsa.PrivateKey` instance as signer. After recent changes we've unified `Signer` interface. From this moment we're able to accept `Signer` instance instead of fixed private key.

Note: there are some signatures with fixed required scheme (like `Container`). We can either leave `ecdsa.PrivateKey` parameter or accept an interface similar to `Signer` but without `Scheme()` method.

**Comment by smallhive** [comment]
Closing according to #219
