### ISSUE TITLE
Pivot for container placement

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-sdk-go#216]
Why does `netmap` accept [any pivot](https://github.com/nspcc-dev/neofs-sdk-go/blob/d20999113a2ec57e6130aa264d818612af4283a2/netmap/netmap.go#L50)? 

In practice a node always [uses](https://github.com/nspcc-dev/neofs-node/blob/v0.28.0-rc.3/cmd/neofs-node/container.go#L358) `cid`. So maybe it would be better to change the interface to accept `cid` to prevent incorrect usage.

**Comment by fyrchik** [comment]
It is really a feature, but I agree `cid` in the signature is more descriptive, especially, given that the function is called `GetContainerNodes`.  Same can be done for `GetPlacementVectors(oid)`.

**Comment by cthulhu-rider** [comment]
Decided to accept typed parameters (`oid.ID`, `cid.ID`).

**Comment by roman-khimov** [comment]
Is there any way to `GetContainerNodes(cid)` and `GetPlacementVectors(cid, oid)`? These look OK for low-level things (with cid/oid), but I'd expect something easier to use from SDK.

**Comment by cthulhu-rider** [comment]
This is the only method for now https://github.com/nspcc-dev/neofs-sdk-go/blob/ae44191e8c04a2b527efef6387c128b3b7b33381/netmap/netmap.go#L169

It'd be nice to have helpers for `cid`, `oid`.
