### ISSUE TITLE
Replace `signature` package from `neofs-api-go`

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#219]
Replace `signature` package from NeoFS API Go [module](https://github.com/nspcc-dev/neofs-api-go/) to the SDK. This business logic should be implemented using `neofscrypto` package API (maybe we need to place it in `crypto/rpc`).

**Comment by roman-khimov** [comment]
It's somewhat ironic that we have the most _generic_ signature hander (operating with `Signer` and abstract `[]data` that can be anything) in SDK now and what we have in api-go's `signature` is certainly higher-level (and not directly tied to the API), even though it's structured differently (using the key directly, for example). So yes, in that sense it's not something we can leave unsolved for 1.0 and we need to move `signature` logic out of api-go.

**Comment by cthulhu-rider** [comment]
after thinking about it again, taking into account #212, I realized that it is better to transfer and make this code private in package `client`
