### ISSUE TITLE
Provide more utility functions over `Client` errors

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#220]
In current implementation SDK provides several functions for `client.Client` error resolving. I propose to cover all error cases and provide more useful functions. For example, [here](https://github.com/nspcc-dev/neofs-s3-gw/pull/404) was a need to not just check whether error is `ACCESS_DENIED` but also get the reason.

**Comment by roman-khimov** [comment]
Why `errors.Is` is not sufficient and we have `client.IsErrObjectNotFound`? I'd expect standard interfaces to work.

**Comment by cthulhu-rider** [comment]
Because client errors currently don't support this: they don't provide `interface{ Is(error) bool }`. Functions like `client.IsErrObjectNotFound` allow the user not to care about it.

**Comment by roman-khimov** [comment]
I'd say this is the problem of these client errors, it's much better to have `errors.Is` (that people use every day) than a dozen of new functions. And we better fix it this way rather than by adding more `IsErr*`.

**Comment by cthulhu-rider** [comment]
Not a problem but the missing feature. I don't mind adding it.

Anyway `client.IsErrX(err)` looks clearer to me than `errors.Is(err, new(apistatus.X))`.
