### ISSUE TITLE
Add `IssuerKey` method to bearer token

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-sdk-go#231]
During update [sdk in neofs-s3-gw](https://github.com/nspcc-dev/neofs-s3-gw/pull/409/files#diff-13f557e3b4e64696e21218c8321e293b2392bba2932cd02b8e3b43a3caeca71d) the following code happens:

```
...
var btoken v2acl.BearerToken
box.Gate.BearerToken.WriteToV2(&btoken)

key, err := keys.NewPublicKeyFromBytes(btoken.GetSignature().GetKey(), elliptic.P256())
...
```  

Maybe we should add method to get the key of the signature from bearer token along with getting the issuer?

**Comment by cthulhu-rider** [comment]
Why `v2acl.BearerToken` instance is needed? It isn't expected to be used.

**Comment by KirillovDenis** [comment]
`bearer.Token` from sdk doesn't provide method to get `key` from signature. So we have to use `v2acl.BearerToken` to access it.

**Comment by smallhive** [comment]
Maybe I'm wrong, but looks like required functionality already added. [Here](https://github.com/nspcc-dev/neofs-sdk-go/blob/master/bearer/bearer.go#LL345C1-L345C1) we have `SigningKeyBytes` function which returns public key bytes.

In this case the code:
```go
var btoken v2acl.BearerToken
box.Gate.BearerToken.WriteToV2(&btoken)

key, err := keys.NewPublicKeyFromBytes(btoken.GetSignature().GetKey(), elliptic.P256())
```
may be rewritten without auxiliary variable in:
```go
key, err := keys.NewPublicKeyFromBytes(box.Gate.BearerToken.SigningKeyBytes(), elliptic.P256())
```
Am I right? @roman-khimov

**Comment by roman-khimov** [comment]
Yeah, c65be6d469db752cfac0247f90ff8efda3918fff has added it. OK, one problem less, even though S3 gw doesn't use it yet, but it can be fixed during SDK update.
