### ISSUE TITLE
Better healthcheck criteria for connection switch

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-sdk-go#283]
Consider storage node in READ ONLY mode. It accepts requests, so pool thinks that node is healthy. But it cannot upload any object because of READ ONLY mode. 

In theory, pool can switch to another node. To do that we need better healthcheck criteria than endpoint info response. Endpoint info response contains [state](https://github.com/nspcc-dev/neofs-api/blob/10f18e4b69ec79991b1a2b83e212d99203f3ee1a/netmap/types.proto#L226). Maybe we can expand this enum with more states related for node health.

/cc @realloc @fyrchik @cthulhu-rider @carpawell

**Comment by cthulhu-rider** [comment]
@alexvanin would it really better than just do try-catch `PUT` with `RO` error resolving (need to be implemented though)?

**Comment by realloc** [comment]
It would be nice to accumulate response statistics (latency, speed, success rate) in client pool and try to load-balance request stream, when possible. Exposing such stats as metrics at the uppr level would also be a very useful feature.

**Comment by alexvanin** [comment]
> and try to load-balance request stream, when possible

Pool was never meant to be load balancer (until now, I guess). Its only purpose is to switch connection after endpoint failover. Load balancing requires some heuristics which are not really obvious.

---

I think we can start with accumulating error rate and average request latency (should we normalize `object.Put()` and `object.Get()` latency because it is related to object size / container policy?)

We can have a list of status codes to count error rate. List of codes to ignore will be harder to maintain compatibility on my opinion.

> Consider new status code for ACL. If pool uses list of ignored status code, it will count new unknown ACL status code in error rate. It might cause a connection switch, don't think it is correct.

Count
- 1024 INTERNAL
- 1025 WRONG_MAGIC_NUMBER
- 1026 SIGNATURE_VERIFICATION_FAIL
- All transport errors like timeout

/cc @KirillovDenis @masterSplinter01

**Comment by realloc** [comment]
> Pool was never meant to be load balancer (until now, I guess). Its only purpose is to switch connection after endpoint failover. Load balancing requires some heuristics which are not really obvious.

Here I mean the pool's intention to use the best endpoint currently available to serve the request, not the global load balancing.

**Comment by cthulhu-rider** [comment]
We can gather and expose some processing metrics during `Pool` communication to start. Later we can provide an interface of peer switching with external weighting algorithm.
