### ISSUE TITLE
Storage Group helpers

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-sdk-go#310]
SDK should support some common functionality for Storage Group creation. Currently, it is only implemented in [`neofs-node`](https://github.com/nspcc-dev/neofs-node/blob/cd71de69a08d87a63fedd7bc4ead54c4ddac8791/pkg/services/object_manager/storagegroup/collect.go#L17) repository and is used only in [CLI](https://github.com/nspcc-dev/neofs-node/blob/master/cmd/neofs-cli/modules/storagegroup/put.go#L92) but the new clients [are expected](https://github.com/nspcc-dev/neofs-rest-gw/pull/37).

Should be implemented in that repo:

1. Storage group creation. Input: CID, members, SDK client (or that could be a method of the client); output: correct storage group that contains *only* physical objects members in the correct order.
2. ~~Storage group validation: Input: CID of storage group: output: validation result (seems like `bool` is enough). Should check if the storage group has been build correctly according to `1.`~~ (see comments)

**Comment by cthulhu-rider** [comment]
Do client applications outside `neofs-node` monorepository need to perform `2` op? I guess it's only needed for pre-store validation on storage nodes and within audit routine. If I'm correct I'd gather validation functionality in `neofs-node` (at least for now).

**Comment by carpawell** [comment]
> Do client applications outside neofs-node monorepository need to perform 2 op

Well, seems like no external use-cases for that, agree.

**Comment by roman-khimov** [comment]
With just №1 left it duplicates #308.
