### ISSUE TITLE
client: Invalid error handling 

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-sdk-go#317]
In `ObjectPutInit`:
https://github.com/nspcc-dev/neofs-sdk-go/blob/4e31b4f2316929aa391fc164d64dfacc7eaa4a92/client/object_put.go#L244-L257
we should check status from `metaHeader` first because it can contain the `access denied` error but now it's missed and we get `missing ID field in the response`.

It seems this affects other client methods too.
Related to #299

**Comment by cthulhu-rider** [comment]
Meta header should have been already checked before the `result` callback. I'll see why it hasn't.
