### ISSUE TITLE
Reload pool configuration on external signal

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-sdk-go#338]
:writing_hand: ...

**Comment by cthulhu-rider** [comment]
I think it's time to move the connection management to the application side. We can work out a generic interface that the library can rely on. Otherwise, library component can become application specific and difficult to maintain.

**Comment by roman-khimov** [comment]
Libraries shouldn't care about signals. They can provide some means to change existing pools though, if needed. But in this particular case an app probably just needs to create a new pool and drop the old one, problem solved.
