### ISSUE TITLE
Provide functionality for static object creation

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#342]
In current version library does not provide any convenient function to prepare and store an object completely on client side. Although the user has all the functionality to perform such a task, the mechanism is rather complicated, because it is required to take into account the current network configuration, independently cut the object into parts, etc.

The script is in high demand, so it is proposed to support it. Already implemented in:
* `neofs-node` https://github.com/nspcc-dev/neofs-node/tree/master/pkg/services/object_manager/transformer
* `distribution` https://github.com/nspcc-dev/distribution/tree/main/registry/storage/driver/neofs

We also need to provide user docs which will help newcomers and even experienced users to faster solve well-known NeoFS tasks.

**Comment by gsmachado** [comment]
🤩 💪

**Comment by cthulhu-rider** [comment]
@gsmachado @mialbu please take a look at the draft #345.
