### ISSUE TITLE
NNS resolving for any zone

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-sdk-go#356]
Now `ResolveContainerName` works only with `.container` zone
https://github.com/nspcc-dev/neofs-sdk-go/blob/da4ddcf337dad1b241f7d4c23d0170258f352703/ns/nns.go#L88

We want to have more general function that accepts any zone (or full domain).

**Comment by KirillovDenis** [comment]
Let's accept the domain as function parameter
https://github.com/nspcc-dev/neofs-sdk-go/blob/da4ddcf337dad1b241f7d4c23d0170258f352703/container/container.go#L425-L429
