### ISSUE TITLE
Include child object IDs in session token for delete

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-sdk-go#360]
Delete of complex object will work only if session token contains info about children. See https://github.com/nspcc-dev/neofs-node/pull/1989 fix in CLI.

We need to support the same logic in pool. 

Blocks: https://github.com/nspcc-dev/neofs-s3-gw/issues/727
It can be blocked by https://github.com/nspcc-dev/neofs-node/issues/1978 because it was re-opened recently.

**Comment by KirillovDenis** [comment]
Let's add a new exported function to find all phy objects by address:
```go

type HeadReceiver interface {
	// Head must return one of:
	// * object header (*object.Object);
	// * structured information about split-chain (*object.SplitInfo).
	Head(id oid.Address) (interface{}, error)
}

func CollectObjectRelatives(HeadReciever, oid.Address) ([]oid.ID, error)
```
Then this can be reused in [sdk](https://github.com/nspcc-dev/neofs-sdk-go/pull/348), [neofs-node](https://github.com/nspcc-dev/neofs-node/pull/1989) and maybe somewhere else.

**Comment by carpawell** [comment]
@KirillovDenis, what about a session and a bearer for that subrequests? should be taken into account in the `HeadReceiver`?

**Comment by cthulhu-rider** [comment]
It's worth to create an interface of object relations' controller, for example:
```
type ObjectRelations interface {
	GetSplitInfo(cnr cid.ID, root oid.ID) (*object.SplitInfo, error)
	ListChildrenByLinker(cnr cid.ID, linker oid.ID) ([]oid.ID, error)
	GetLeftSibling(cnr cid.ID, right oid.ID) (oid.ID, error)
}

func ListAllRelations(rels ObjectRelations, cnr cid.ID, root oid.ID) ([]oid.ID, error)
```

Implementations:
* client
* client pool
* app-side caches

**Comment by KirillovDenis** [comment]
>	GetSplitInfo(cnr cid.ID, root oid.ID) (*object.SplitInfo, error)
>	ListChildrenByLinker(cnr cid.ID, linker oid.ID) ([]oid.ID, error)
>	GetLeftSibling(cnr cid.ID, right oid.ID) (oid.ID, error)

It seems we also need then:
```go
FindSiblingBySplitID(cnr cid.ID, id *SplitID) ([]oid.ID, error)
FindSiblingByParentID(cnr cid.ID, root oid.ID) ([]oid.ID, error)
```

Maybe interface with `Head` and `Search` will be enough?

**Comment by cthulhu-rider** [comment]
@KirillovDenis yeah this looks good to me since we play with identifiers only. `Head`+ `Search` would be too abstract complicating potential improvements with caching.

Btw why do we need `FindSiblingByParentID`?

**Comment by KirillovDenis** [comment]
Because of https://github.com/nspcc-dev/neofs-node/blob/d8d3588e1b824af37c34f16bef89e5a2af71f70b/cmd/neofs-cli/modules/object/util.go#L446

It seems we are looking for linking object?
