### ISSUE TITLE
Consider prometheus histogram metrics in pool

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-sdk-go#365]
Request time distribution looks kinda cool: https://github.com/nspcc-dev/neo-go/pull/2750
Probably we can adopt metric interface to provide simple histogram data to service apps.

**Comment by alexvanin** [comment]
- We can discuss tight integration of prometheus and pool.
- We can return actual request durations from pool instead of avg.

**Comment by KirillovDenis** [comment]
> return actual request durations

In this case I suppose we can have only last `n` requests durations for each methods (we can configure `n` in pool params)

> have callback for each pool request

We can define something like this:

```
type RequestCallback func(RequestInfo)

type RequestInfo struct {
	Address    string
	MethodName string
	Elapsed    time.Duration
}
```

Both options are possible and require almost the same efforts

**Comment by alexvanin** [comment]
Callback implementation looks very nice. Let's go for that.
