### ISSUE TITLE
Implicit internal processing option of the code status

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#377]
https://pkg.go.dev/github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.7/client#PrmInit.ResolveNeoFSFailures option makes client to resolve status failures from the server and return them in `error` value. It looks transparent if the method call happens "next to" client initialization. However, when calling the method in a separate function around the client, it is not clear whether the status code should be resolved, or whether it is already in error. The only workaround I see is to pass the resolving flag to such functions and carry it everywhere with you. It is proposed to strengthen the resolution of statuses at the type level in order to avoid double work or unexpected results.

**Comment by roman-khimov** [comment]
So the issue is client's modality wrt this option? Because the other way to see it is that this option can be changed on an already existing client, but it looks like this can't happen (`PrmInit` is copied).

**Comment by roman-khimov** [comment]
Can be solved with raw/usable client split, but it works as of now as well, just needs a little more care from the SDK user. So not a top priority.

**Comment by notimetoname** [comment]
So basically the issue may be dropped in favor of #406?

**Comment by roman-khimov** [comment]
Will be solved by #406.
