### ISSUE TITLE
Add session tokens caching

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-sdk-go#38]
Consider adding a session token caching layer (or creating tokens for every request with `client.WithKey` call option). It can be used for anonymous requests https://github.com/nspcc-dev/neofs-s3-gw/issues/271.

Currently session tokens are refreshed only for `client.DefaultPrivateKey` when storage nodes come alive.

**Comment by alexvanin** [comment]
I want to test it with HTTP Gateway, however api-go->sdk-go migration blocks it. Thus it will be merged after migration.
