### ISSUE TITLE
Do not serialize structures for static signer

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-sdk-go#400]
It can be optimized out, see https://github.com/nspcc-dev/neofs-sdk-go/pull/398#discussion_r1172312597

**Comment by smallhive** [comment]
It is obvious, that `StaticSigner` faster and cheaper then regular signer. Despite it we shouldn't have two different methods like `Calculate` and `CalculateLazy`. It may lead to misunderstanding to customer, which func should be use to calculate signature.

Instead it I suggest to [change](https://github.com/nspcc-dev/neofs-sdk-go/pull/436/files#diff-066e1fb6f239f1e36aee2411ec1c438d371dcafb91ff853b6e33295a000cf662R104) `Calculate` func interface from
```go
func (x *Signature) Calculate(signer Signer, data []byte) error
```
to
```go
func (x *Signature) Calculate(signer Signer, dataSrc func() []byte) error {
```

Of course, it leads to some changes in code, but removes misunderstanding. This [changed](https://github.com/nspcc-dev/neofs-sdk-go/pull/436/files#diff-066e1fb6f239f1e36aee2411ec1c438d371dcafb91ff853b6e33295a000cf662R104) variant has the same performance:

```
$ go test -bench=. -benchmem
goos: linux
goarch: amd64
pkg: github.com/nspcc-dev/neofs-sdk-go/container
cpu: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
BenchmarkCalculate-16                      27002             43873 ns/op            5396 B/op         76 allocs/op
BenchmarkCalculateLazy-16                  27144             44347 ns/op            5396 B/op         76 allocs/op
BenchmarkCalculateLazyStatic-16          1535890               887.0 ns/op           272 B/op          4 allocs/op
BenchmarkCalculateLazySingle-16            27273             46403 ns/op            5396 B/op         76 allocs/op
PASS
ok      github.com/nspcc-dev/neofs-sdk-go/container     6.896s
```

Description:
* BenchmarkCalculate - current signer function
* BenchmarkCalculateLazy - checks if signer is `Static` and do all staff or call regualar `Calculate`
* BenchmarkCalculateLazyStatic - working only with StaticSigner, just for information
* BenchmarkCalculateLazySingle - Our target function

Conslusion:
* Use single function Calculate
* Change its interface
* Update the code
* Enjoy dramatical speed increasing with StaticSigner situations

**Comment by roman-khimov** [comment]
Passing a function means creating some lambda function in 99% of use cases which is just not fun. How about 
```
type MarshalledStably interface {
    StableMarshal([]byte) []byte
}
func (x *Signature) Calculate(signer Signer, data []byte) error {}
func (x *Signature) CalculateMarshalled(signer Signer, smth MarshalledStably) error {}
```
IIRC we calculate signatures for something with `StableMarshal()` in 99% of the cases.

**Comment by smallhive** [comment]
Do you mean left current `Calculate` as is, append new `CalculateMarshalled` where we will implement _Lazy_ functionality?
I don't mind, even more - I like this approach.

**Comment by roman-khimov** [comment]
Yeah, generic `Calculate` can be useful anyway, but `marshalled` one can be lazy or not depending on the implementation. Static signer will obviously optimize it.

**Comment by notimetoname** [comment]
> Passing a function means creating some lambda function in 99% of use cases which is just not fun.

@roman-khimov, do you mean readability or another reasons?

**Comment by roman-khimov** [comment]
Mostly that. Performance-wise there will also be a difference, but a tiny one.
