### ISSUE TITLE
Make ObjectReader/ObjectRangeReader compatible with io.Closer/io.ReaderCloser

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-sdk-go#405]
Consider nspcc-dev/neo-go#2995, there is an oracle subsystem that can do requests via HTTP and via NeoFS protocol. In the successful case we get some `io.ReaderCloser` for HTTP, but we have some really strange thing for NeoFS, it's `io.Reader`, but it's not `io.ReaderCloser` because its Close method returns some alien things. This means we can't unify some of the code for these cases even though they look very similar. Implementing proper `io.Closer` would be make for a much better library interface.

**Comment by cthulhu-rider** [comment]
can be done similar to https://github.com/nspcc-dev/neofs-sdk-go/pull/382#discussion_r1175698923
