### ISSUE TITLE
Accept mandatory action parameters as plain old method arguments 

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-sdk-go#412]
We're overly reliant on functional parameters across the whole SDK. They're somewhat useful for optional things (that theoretically (but YAGNI) can grow), but they lead to code bloat and a lot of misunderstanding for mandatory, required things. When people see
```
Do(ctx context.Context, s string, i int, optional Something) (result, error)
```
they understand easily what's required and what's not, they can see the types, their compiler won't allow them to call the function without these parameters or wrong types of these parameters. Compare that to
```
Do(ctx context.Context, param PrmDo) (result, error)
```
It requires a lot more mental effort to understand what's going on, set required parameters and then any code calling `Do` looks like
```
var p PrmDo
p.SetMandatory1(s)
p.SetMandatory2(i)
r, err = Do(ctx, p)
```
instead of
```
r, err = Do(ctx, s, i, optional{})
```
So the proposal is to use functional parameters only for optional things (where we have them) and have plain old function parameters for anything mandatory (and these things don't change, really, to put a container you need a container, to get an object you need OID and CID, there is no way around it).

So instead of:
```
ContainerPut(ctx context.Context, prm PrmContainerPut)
```
We'd get something more like:
```
ContainerPut(ctx context.Context, cnr container.Container, opts ContainerPutOptional)
```
(it's just an example though).

Related to #390 and #380.

**Comment by cthulhu-rider** [comment]
overall, proposal LGTM

Talking about functional parameters in general... They provide more power for introducing compatible API extensions than explicit one-by-one parameters. For example, when you realize that your `uint32` mandatory parameter is too narrow and you need `uint64` - it's much easier to add one more setter than completely new method. Also, it's makes code a bit clearer

**Comment by notimetoname** [comment]
@roman-khimov, a few questions:

1. what if a mandatory args number is big enough (let's say, 5+)?
2. how would we solve @cthulhu-rider's problems? would we? or just deprecation and a new method OK?
3. what do you think about quite a common pattern with func args (`WithXXX()`)?

**Comment by roman-khimov** [comment]
1. This is rare and can be considered case by case, I'd say that having 5 parameters is not the end of the world if that's how something works.
2. Method is a verb, we can have as many verbs as we need. Changes like uint32/uint64 don't happen very often. When they do people have to change something in their code anyway to make use of new features. When people change code it's not really critical if they use a new setter or a new function name. Old methods can be deprecated easily as well, then some transition period, then they're gone, easy as that.
3. Frankly, I'd prefer simple structures, they work just fine and can be extended easily. But `WithSmth` can be OK for optional things.

**Comment by smallhive** [comment]
Deriving mandatory arguments from structure, will made the code more simple. And how someone who tried to use SDK, I should say it would save me time, if I had this feature a month ago

**Comment by amlwwalker** [comment]
Interesting as I think this is sort of how a much earlier version of the SDK worked IIRC. Personally have got used to functional parameters now and as a result have learnt to prefer them to long function definitions

**Comment by smallhive** [comment]
Decided to make two PRs:
- [One](https://github.com/nspcc-dev/neofs-sdk-go/pull/424) about container operations, it is ready to review.
- [Second](https://github.com/nspcc-dev/neofs-sdk-go/pull/425) about objects operations. It is in draft state. Check please, if this way is ok, I will continue. @roman-khimov @cthulhu-rider @notimetoname
