### ISSUE TITLE
Make pool statistics optional

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-sdk-go#431]
In many cases it's useless, so there has to be a knob for it.

**Comment by cthulhu-rider** [comment]
abstraction through exported interface defaulting to no-op fits well here

**Comment by roman-khimov** [comment]
It can also be counted in many different ways, average/min/max/median/histogram/protocol errors/logic errors, whatever. So in fact it can be decoupled completely into a thing of its own with just one callback (`reg(method, time, error)`). We can then accept it as a `Pool` parameter and provide `Statistics` we have as a simple implementation of it (that is used by gateways), but default to no-op.

**Comment by roman-khimov** [comment]
The next questions could be:
 * how to count statistics for a single node client
 * how to make use of it for reputation

Not that I'd like to answer those immediately, but...
