### ISSUE TITLE
Provide easier way to configure a pool with a simple set of endpoints

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-sdk-go#432]
Weighted ones are fun, but also irrelevant in many cases. Simple things should be done easily, so some more convenient way to pass a set of endpoints to the pool is needed.

**Comment by smallhive** [comment]
Now we have:
```
endpoints := []string{"grpc://localhost:8080", "grpcs://localhost:8081"}
pool, _ := pool.New(endpoints, pool.DefaultOptions(signer))
```
