### ISSUE TITLE
Move some `container` package methods to `container.Container`

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-sdk-go#433]
Why on earth do we do `container.SetCreationTime(cnr, t)` when this could be `cnr.SetCreationTime(t)`? It'd be OK if this was some unrelated package that is doing something to `container.Container` (like `client.SyncContainerWithNetwork`), but it's the same `container` with the same dependencies and things. Almost all of the functions from `container` could be methods making them easier to use.

**Comment by notimetoname** [comment]
As i remember the idea was to position the func as a helper funs. It is impossible to set `time.Duration` in any way cause it is not even a field in `v2` version (but a string attribute instead). Seems like alphabet [does not check it](https://github.com/nspcc-dev/neofs-node/blob/ebd0631b73ed7003f514d7088f90561b550f706e/pkg/innerring/processors/container/process_container.go#L67-L95).  It [can be omitted](https://github.com/nspcc-dev/neofs-node/blob/ebd0631b73ed7003f514d7088f90561b550f706e/cmd/neofs-cli/modules/container/create.go#L162) at all in CLI and is not required in the API. So it is kinda optional thing. But i would make it a method too, i think.
cc @cthulhu-rider

**Comment by roman-khimov** [comment]
We've got api-go `v2` for on-the-wire things that can be strictly limited to things that have exact message-level representation. But SDK is for people. `container.CalculateID`? `container.Name`? `container.WriteDomain`? No, thanks.

**Comment by smallhive** [comment]
I think funcs like `container.SetCreationTime` should be the part of the container. There is not profit to have it as a separate functions. This data sets inside the container attributes, we just add the different native method for this

**Comment by roman-khimov** [comment]
`CalculateIDFromBinary` btw is a natural thing for `container/id` to have.

**Comment by cthulhu-rider** [comment]
me personally don't like sugared methods which doesn't use private elements of type/package, this saturates the interface. `SetCreationTime` uses private stuff, so it's better to make it a method

**Comment by notimetoname** [comment]
**I am for method too, just reminding why it was done that way**

> There is not profit to have it as a separate functions.

Semantics. All the setters set fields. You can not set fields without setters. But you can add creation time via `SetAttribute` and a key that is just [a const and is available](https://github.com/nspcc-dev/neofs-api/blob/b8476e4b5f24e64388bd0532e2652fec4ba121db/container/types.proto#L60-L61) and fixed.

**Comment by cthulhu-rider** [comment]
@notimetoname ur right, but not in this case. Constant is tightly bound to the V2 protocol revision, so, in theory, in V3 it may be `TIMESTAMP` or anything else. Method could cover both cases, function doesn't
