### ISSUE TITLE
Placement functions are buggy

### ISSUE THREAD

**Issue by notimetoname** [nspcc-dev/neofs-sdk-go#438]
Placement is built using `Capacity` and `Price` attrs as a criterion for `HRW` sorting. But looking for a minimum `Price` in the placement vector behaves strangely: when it finds `0` `Price` it [saves](https://github.com/nspcc-dev/neofs-sdk-go/blob/395050dfb0eadf0f16e40a23f7b2d435e58234f5/netmap/aggregator.go#L105-L107) _the next element as the minimum_.
In short, consider [the test](https://github.com/notimetoname/neofs-sdk-go/blob/904c5b380686d3fc93769de13e3dc01dc62230e9/netmap/aggregator_test.go#L9).

**Comment by roman-khimov** [comment]
Fixing them is likely to cause some data storm, maybe that's where we could also fix the node wrt its load data "placement".
