### ISSUE TITLE
Make `slicer` more explicit

### ISSUE THREAD

**Issue by notimetoname** [nspcc-dev/neofs-sdk-go#441]
I would not go variadic [here](https://github.com/nspcc-dev/neofs-sdk-go/blob/79edfa63bbc9d1a4bf121a82182117d2247a2ade/object/slicer/slicer.go#L296). It led to https://github.com/nspcc-dev/neofs-node/pull/2375. I remember my thoughts: "will fill it later, let's check that it works in general" and then I forget it of course cause I did not see any weird `nil` calls.
Also, I would go with `object.Attribute` instead of `string`.

**Comment by cthulhu-rider** [comment]
current API is purely based on built-in and stdlib types and that's convenient, lets add a dedicated method for `object.Attribute` case

**Comment by smallhive** [comment]
The task is no more actual. It was connected to not using attributes like `[]string`. After #442 attributes are `[]object.Attribute`

**Comment by roman-khimov** [comment]
And they're not variadic.
