### ISSUE TITLE
`Slicer` interface is not generic enough for objects

### ISSUE THREAD

**Issue by notimetoname** [nspcc-dev/neofs-sdk-go#442]
It [allows specifying](https://github.com/nspcc-dev/neofs-sdk-go/blob/79edfa63bbc9d1a4bf121a82182117d2247a2ade/object/slicer/slicer.go#L79) container, owner and _some options_ (i dunno what is the difference b/w them and why container is container but `objectPayloadLimit` is an `Option`). Later it will also allow specifying [attributes](https://github.com/nspcc-dev/neofs-sdk-go/blob/79edfa63bbc9d1a4bf121a82182117d2247a2ade/object/slicer/slicer.go#L140).

So at least:
1. Why are they separated?
    1.1 b/w `New` and `Slice` calls?
    1.2 b/w func args and `Option` struct?
2. Why not just pass `object.Object`? If we extend the object's header we will have to change the `Slicer`'s signature (or extend `Options` but see `1.2`). Filling the header with a provided header looks natural. As another argument: it is not possible to [slice SG](https://github.com/nspcc-dev/neofs-node/pull/2375) object just because there is no way to pass `object.Type` (`Options` can be but I absolutely don't like it and don't get it. That is why the issue (and not a PR) is created).

**Comment by roman-khimov** [comment]
What bugs me is that we don't a clear `object.Header` type which could be much more useful than the CID/OID split of the same thing. But that's a different thing.

IIUC if we're to pass `object.Object` it'll solve most of the problems, but we'll still have a question of homomorphic hash and payload limit which inherently have to be some options.

**Comment by roman-khimov** [comment]
`NewDataSlicer` can't accept a session token which can also be a problem requiring user to implement `slicer.ObjectWriter`.

**Comment by notimetoname** [comment]
> IIUC if we're to pass `object.Object` it'll solve most of the problems

Yes, it would solve all the problems I see at this moment.

> but we'll still have a question of homomorphic hash and payload limit which inherently have to be some options.

It may be considered as a `New` args cause it tunes the `Slicer` while `object.Object` may be a `Slice` call's param cause it defines an object it slices but _not how_ it would be sliced. At least that is what I can understand. The current API is not clear to me.

Also, I wanted to highlight that I do not get _how_ `Slicer` should solve problems: why does it accept one container but many attribute sets? Is it expected to be reused? Why with a single container and a single signer (owner)? Why only one session can be attached? Is it client-side oriented?
