### ISSUE TITLE
Describe pool session management and provide a knob to turn it off

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-sdk-go#449]
See https://github.com/nspcc-dev/neofs-sdk-go/pull/434#discussion_r1228064058

We need better documentation for pool's session management and implications of various parameters passed to its methods. We also need some way to disable it per-request.

**Comment by smallhive** [comment]
Do we want to have auto sessions enabled or disabled by default?
@roman-khimov

**Comment by roman-khimov** [comment]
Enabled, of course. Using non-automatic sessions for pool is a very specific behavior for very specific cases.
