### ISSUE TITLE
Integration tests fail with the latest NeoFS AIO

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#572]
integration tests started to fail with the latest https://github.com/nspcc-dev/neofs-aio. Looks like https://github.com/nspcc-dev/neofs-aio/pull/75 changed smth meaningful for testing, while AIO itself works fine

* see https://github.com/nspcc-dev/neofs-sdk-go/actions/runs/8424264613/job/23067769667?pr=564

according to the log, everything is started fine. But `context deadline exceeded: failed to start container` anyway. May be related to AIO container healthiness, but idk how it's checked. @smallhive assist will be appreciated

**Comment by roman-khimov** [comment]
There are self-checks in `init-aio.sh` and it prints `aio container started` when it's ready. This should be the line to check for any third-party user like SDK tests.

**Comment by roman-khimov** [comment]
Fixed by #576, missed this issue.
