### ISSUE TITLE
object: Provide helper methods for system attributes

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#630]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when user needs to do following to set the object expiration:
```go
		attrs := obj.Attributes()
		var expAttrFound bool
		expAttrValue := strconv.FormatUint(exp, 10)

		for i := range attrs {
			if attrs[i].Key() == object.AttributeExpirationEpoch {
				attrs[i].SetValue(expAttrValue)
				expAttrFound = true
				break
			}
		}

		if !expAttrFound {
			index := len(attrs)
			attrs = append(attrs, object.Attribute{})
			attrs[index].SetKey(object.AttributeExpirationEpoch)
			attrs[index].SetValue(expAttrValue)
		}

		obj.SetAttributes(attrs...)
```
he should care about: expiration is an attribute, it should be unique and formatted correctly

## Describe the solution you'd like
add [Container.SetCreationTime](https://pkg.go.dev/github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.12/container#Container.SetCreationTime) + [Container.CreatedAt](https://pkg.go.dev/github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.12/container#Container.CreatedAt) analogs

## Describe alternatives you've considered
keep tryhard

## Additional context
https://github.com/nspcc-dev/neofs-node/pull/2943

**Comment by carpawell** [comment]
We also have https://github.com/nspcc-dev/neofs-sdk-go/issues/253 with some messages there.

**Comment by cthulhu-rider** [comment]
oh these issue names...
