### ISSUE TITLE
Reuse available capacity of slices in `CopyTo`

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#674]
see https://github.com/nspcc-dev/neofs-sdk-go/pull/667#discussion_r1897793518

benchmarks first

**Comment by roman-khimov** [comment]
We can't if we're treating `CopyTo()` as deep copy. You'll append in one instance, then append in another and then the fun will start.

**Comment by cthulhu-rider** [comment]
deep copy means src is preserved. This is about dst

**Comment by roman-khimov** [comment]
It means `src` and `dst` have nothing shared. In your patch they do share a slice.

**Comment by cthulhu-rider** [comment]
misunderstood then
