### ISSUE TITLE
priority support for http gw peers

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-sdk-go#74]
There is no support for a fallback mode, when the second peer will only be used if the first is unreachable.
Please add a priority parameter, the same way as [SRV](https://www.cloudflare.com/learning/dns/dns-records/dns-srv-record/) record does. It also be nice to have a support for peers configuration via SRV DNS record.

**Comment by KirillovDenis** [comment]
It seems this issue should be moved to https://github.com/nspcc-dev/neofs-sdk-go because the pool must be change to support this feature.
