### ISSUE TITLE
Transform `client.Client` interface to structure

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-sdk-go#89]
Defining a `client.Client` as an interface makes no sense. If it is necessary to override the client API, the user should define its interface on his side. It should also be noted that the client's current API does not allow overriding its behavior (write-only parameters and read-only results).

Note: transformation is a breaking change since all client methods are implemented on pointers.

**Comment by alexvanin** [comment]
A while ago pool has been using client.Client interface but now this is gone, so one more reason to drop client interface.
