### ISSUE TITLE
TLS endpoint support in conenction pool

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-sdk-go#9]
In NeoFS Node v0.21.0 we introduced TLS support for gRPC servers. As we [discussed](https://github.com/nspcc-dev/neofs-node/issues/455), this feature required explicit schema declaration for endpoints. We went with `grpc[s]://host:port` scheme with a note that omitted scheme parsed as `grpc://`. This parsing routine supported in neofs-api-go v1.27.0 as an [option](https://github.com/nspcc-dev/neofs-api-go/pull/290/files#diff-4e3a84d6de1cd6cc2439652e17a86a027482419186aa958f31a6efe84711dac4R153-R178) for `pkg/client`. 

Service applications such as http-gw and s3-gw use connection pool from this repo. This connection pool works directly with gRPC connections. TLS configuration passed at dial stage, therefore scheme parser should be implemented there too.

---

Maybe working with raw gRPC connections is not that great in general. NeoFS API does not define any transport implementations. Right now we are using gRPC, but we are not limited to it (see Twirp or DRPC). The idea of `pkg/client` is to hide transport implementation details. So I want you to reconsider the role of gRPC connection pool and maybe look more into `pkg/client` pool. It also has some flaws: lack of control over underlying connection as the prior example. But I think we can work on it together and come up with desired solution.

/cc @roman-khimov @realloc

**Comment by roman-khimov** [comment]
Yep, there is `WithDialTimeout` and it's enough for `NodeConnectionTimeout`.

**Comment by roman-khimov** [comment]
As of now we can just drop keepalive tuning from gateway options, if it ever to be needed (but I doubt that) it could be added into client package itself. So:
 * drop direct gRPC connections, let `client.New` set up the connection
 * use `WithURIAddress` to support secure connections (see nspcc-dev/neo-go#2003 also)
